### ISSUE TITLE
Error java: module not found: org.libheiffx

### ISSUE THREAD

**Issue by trantronghien** [lanthale/LibHeifFX#1]
I have done like instruction readme and then added `requires org.libheiffx;` in `module-info.java` but the error keeps popping up, I'm using intellij idea. please help me

**Comment by lanthale** [comment]
Can you give me more details to help. Which JDK Version are you using and which javafx version ? Which build system ? Do you use java modules or do you develop a class path application ?

**Comment by lanthale** [comment]
No response -> close the issue

**Comment by trantronghien85** [comment]
- I used [javafx-maven-plugin](https://github.com/openjfx/javafx-maven-plugin) to build JavaFX application. but `javafx-maven-plugin` does not support sdk 18. It only supports JDK 11.
- Error occurred: `Unsupported major.minor version 63.0`
